variable "name" {}
variable "project" {}
variable "regiongcp" {}
variable "initial_node_count" {}
variable "machine_type" {}
variable "description_dev" {}
variable "description_prod" {}
variable "version" {}
variable "enviroment" {}
